# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c5dae342bd43fdd71d083130c98107c5905377c7b3af840196a4d099d87a8a267ead947bb4d1117daa98ccae9fd7d944eb0b00aeaad1c4e51274fa430a45114

test:
  secret_key_base: 6282a986f3a020db3aa7e3d3cb23f05ca619695abbae6888bff7783e4f14ce04440b5d406e1032bb83279128961c724cb95e00a69b82f52ea43a4d732682c551

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
